// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJeXHzQ3n2L-zA75wamsjtPYnHZfB33H8',
    appId: '1:1080302989825:web:4024b142d6e1d2ef6b0600',
    messagingSenderId: '1080302989825',
    projectId: 'ecosphere-g23',
    authDomain: 'ecosphere-g23.firebaseapp.com',
    storageBucket: 'ecosphere-g23.firebasestorage.app',
    measurementId: 'G-RWXQH5WVX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuoZeswc4D9HpvUy8h9ga2MUxziu1F4Z0',
    appId: '1:1080302989825:android:674f19c109f6ca976b0600',
    messagingSenderId: '1080302989825',
    projectId: 'ecosphere-g23',
    storageBucket: 'ecosphere-g23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZzJHGgTsDjyWA5JGUoj_ygISDPfUtrhM',
    appId: '1:1080302989825:ios:49e54e6de9e739d06b0600',
    messagingSenderId: '1080302989825',
    projectId: 'ecosphere-g23',
    storageBucket: 'ecosphere-g23.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZzJHGgTsDjyWA5JGUoj_ygISDPfUtrhM',
    appId: '1:1080302989825:ios:49e54e6de9e739d06b0600',
    messagingSenderId: '1080302989825',
    projectId: 'ecosphere-g23',
    storageBucket: 'ecosphere-g23.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJeXHzQ3n2L-zA75wamsjtPYnHZfB33H8',
    appId: '1:1080302989825:web:d642bcd7cf01b78c6b0600',
    messagingSenderId: '1080302989825',
    projectId: 'ecosphere-g23',
    authDomain: 'ecosphere-g23.firebaseapp.com',
    storageBucket: 'ecosphere-g23.firebasestorage.app',
    measurementId: 'G-3FZ66DRLTG',
  );
}
