name: Flutter CI

on:
  pull_request:
    branches:
      - main

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install dependencies
        run: cd flutter_app && flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build APK (release)
        run: flutter build apk --release
